### ISSUE TITLE
Support for swipe left/right in Cells/CellGroup

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad#111]
I would love to start using mad-components in PleaseMove, but in my current navigation cells I have an option to add "swipe right to get option to delete" behaviour. This is not currently possible with mad-components' cells
![image](https://github.com/equinor/mad/assets/22524448/72e1dc55-66e2-429c-87c8-b55c4429cb93)

Is this something that is possible to add in mad components? Would it even make sense to add it?

**Comment by HaakonSvane** [comment]
There are many ways to tackle this issue. I have sorted them on the amount of freedom the provide the users from high to low (low freedom is not necessarily good in this case, though it is in IRL):

1. Tell the users to implement their own swipeable functionality on our cells
2. Wrap a solid swipable-implementation to ensure that at least ([React Native Gesture Handler](https://docs.swmansion.com/react-native-gesture-handler/docs/api/components/swipeable/) has a very nice one) all apps use the same library, but force them to implement it themselves.
3. Expose a template system: a right and left swipe group containing a list of configuration objects. An object would contain fields such as `title`, `icon`, `onPress` and `color`.
4. Add props to the cells that predefine the objects mentioned in the previous example. For example, we allow users to add a "delete item".

Personally, I like #3 the most. I think it would make life super nice for developers to have this ready out of the box for all Cells. 

We then need to decide whether or not this should defined on the Cell, the NavigationCell, or as a separate component instead. The latter provides the most functionality, but also opens up for less consistent design.

I think it is also important to keep in mind that this feature is likely to introduce React Native Gesture Handler into our peerDependencies. I do think it is fair to require some of the most core libraries that exists for our components library, but we should be very careful when considering features that will require this to keep maintenance and bloating to a minimum.
