### ISSUE TITLE
ServiceMessage

### ISSUE THREAD

**Issue by dansvend** [equinor/mad#116]
Add `ServiceMessage` component from [equinor/mad-expo-core](https://github.com/equinor/mad-expo-core).

**Comment by HaakonSvane** [comment]
We have been discussing a design for this here: https://www.figma.com/file/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?type=design&node-id=541-38571&t=sEePpUdzeFOkovNV-0

It should work well with the rest of the alert systems in the apps, so it should perhaps be implemented with that in mind. @tormodAase has started an implementation of toasts that we will use in mad components. This might be what will become service messages in the future as well

**Comment by dansvend** [comment]
Duplicate of #266
