### ISSUE TITLE
Dialog component

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad#126]
https://storybook.eds.equinor.com/?path=/docs/feedback-dialog--docs

Needed in Code of Conduct

**Comment by HaakonSvane** [comment]
👍👍

What context is this being used in Code of Conduct? At first glance, this feels very similar to the React Native Alert component. Do you think this should replace all uses of the Alert component?
@EmilieOlsen any inputs?

**Comment by tormodAase** [comment]
It would fit better into the EDS design, and it would have more capabilities. For instance, the message can contain more than just text.

![image](https://github.com/equinor/mad/assets/22524448/c330ae6d-3f9c-4400-b222-df861921b73b)
Here is where we will use it (https://www.figma.com/file/eWU48zN1HzZ7GISoGbhTos/Code-of-Conduct?type=design&node-id=1811-28183&mode=design&t=2ZM4Ucswmr8cWxwX-0)

**Comment by tormodAase** [comment]
I'm currently implementing it in a way that would make the API almost identical with `eds-core-react` api

**Comment by tormodAase** [comment]
But I also plan to create a "simple" version that would be just as easy to use as React Native Alert
