### ISSUE TITLE
Unable to run chronicles on Node.js 18

### ISSUE THREAD

**Issue by dansvend** [equinor/mad#139]
Can't run chronicles when running the following software:
- Node.js 18.13.0
- pnpm 8.6.11
![image](https://github.com/equinor/mad/assets/47424077/763acaa4-fddf-47e0-8719-3fa1d3082833)

**Comment by HaakonSvane** [comment]
It is likely the pnpm version 8 that is causing the issue (see: #115 for some more info). If you are able to fix this issue by downgrading to 7.x.y, should we instead rename this issue to "upgrade repository to pnpm 8"
