### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by dansvend** [equinor/mad#141]
Create an `Autocomplete` component which allows users to choose one or multiple options from a list, similar to [Autocomplete](https://storybook.eds.equinor.com/?path=/docs/inputs-autocomplete--docs) from EDS.

**Comment by Sandtory** [comment]
https://www.figma.com/file/DddCDZoFicduHUyfRCSUjG4k/Inspection?type=design&node-id=4063-86873&mode=design&t=bRH33Ag5AcagkKhz-0
