### ISSUE TITLE
Add release please

### ISSUE THREAD

**Issue by dansvend** [equinor/mad#158]
### Package / App

Other

### Description

Add [Release Please](https://github.com/google-github-actions/release-please-action) GitHub Action.

- [ ] Add `release-type` variable which can be `node` or `expo`.
- [ ] Add docs for writing commit messages ([Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)).

**Comment by HaakonSvane** [comment]
@dansvend can this be closed as not planned ?

**Comment by dansvend** [comment]
@HaakonSvane Yes, sir 🫡
