### ISSUE TITLE
`useEDS`: Load `MaterialCommunityIcons`

### ISSUE THREAD

**Issue by dansvend** [equinor/mad#167]
### Package / App

MAD Components

### Description

Load `MaterialCommunityIcons` in `useEDS` to make sure icons are preloaded.

**Comment by HaakonSvane** [comment]
@dansvend Do you have any documentation on what to use for preloading? I can't find information on it in the expo vector icons docs

**Comment by dansvend** [comment]
> @dansvend Do you have any documentation on what to use for preloading? I can't find information on it in the expo vector icons docs

I see we use [useFonts](https://docs.expo.dev/versions/latest/sdk/font/#usefontsmap) in [useEDS](https://github.com/equinor/mad/blob/main/packages/components/src/hooks/useEDS.ts).

This is the code in `useCachedResources` for preloading fonts that was initialised in an Expo SDK 47 project where switching `FontAwesome` with `MaterialCommunityIcons` does the trick.

```TSX
// Load fonts
await Font.loadAsync({
  ...FontAwesome.font,
  'space-mono': require('../assets/fonts/SpaceMono-Regular.ttf'),
});
```

**Comment by dansvend** [comment]
Duplicate of #277
