### ISSUE TITLE
Auto-reload Malfunction After Saving

### ISSUE THREAD

**Issue by Jonas-Omdal** [equinor/mad#208]
### Package / App

MAD Components

### Version

0.0.0

### What happened?

Upon saving changes (most of the times), the app automatically reloads and redirects the user to the Discover screen. Once redirected, you cannot interact with any on-screen elements. When attempting to trigger a reload using the 'R' key in the simulator nothing happends and the 'R' command in the terminal is also unresponsive. 
In order to see changes you have to re-run the application, a process that is considerably time-consuming.

**Comment by tormodAase** [comment]
Just to add some info. This is related to `@equinor/mad-navigation`. Once we import `createNativeStackNavigator` and `createBottomStackNavigator` from `react-navigation` instead of `mad-navigation`, the problem disappears. I will look into it
