### ISSUE TITLE
Create `@equinor/mad-dfw`

### ISSUE THREAD

**Issue by HaakonSvane** [equinor/mad#214]
### Package / App

Other

### Description

We need a package for all things Digital Field Worker related. The package should include:

- Echo 3D web navigators and screens
- Display components (work order, tag, equipment, notification etc)
- Notification cells

**Comment by HaakonSvane** [comment]
@EmilieOlsen 

Could you provide some designs for the following:
- Work order header 
- Tag header
- Equipment header
- Notification header

**Comment by EmilieOlsen** [comment]
Sorry for the delay!
Different variations in Figma: https://www.figma.com/file/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?type=design&node-id=1167%3A1486&mode=design&t=0oFPgV6n4i1MM6jP-1

Tablet:
![image](https://github.com/equinor/mad/assets/111871753/91956119-7a89-4440-b6a1-e6a75ed5281e)
![image](https://github.com/equinor/mad/assets/111871753/b6c2716c-5f86-4283-a2be-391586940b89)

Mobile:
![image](https://github.com/equinor/mad/assets/111871753/7ffa78f9-3462-494a-89c0-5810ba244324)
