### ISSUE TITLE
The login screen should follow the design

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad#233]
### Package / App

Other

### Description

`mad-core` currently has a login screen that provides the needed functionality. However, the design has not been looked at yet.

We should implement the design provided in [Figma](https://www.figma.com/file/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?type=design&node-id=1%3A2&mode=dev)

### Other info

Note: The design in figma is not yet considered the final design. This issue is therefore not considered ready for development

**Comment by KaterynaBasik** [comment]
@EmilieOlsen, we need your help with this

**Comment by EmilieOlsen** [comment]
Suggestion:
![image](https://github.com/equinor/mad/assets/111871753/4ad84fc3-7482-4515-86e1-2b8b8c4d7ce7)

Any thoughts?

https://www.figma.com/file/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?type=design&node-id=1%3A2&mode=design&t=h9qC2oQoDBopZ5yv-1

**Comment by tormodAase** [comment]
@EmilieOlsen Awesome!

In my opinion the red theme is very different from how the rest of the application(s) will look. Would it be more aligned with the rest of the app if you use moss green (#007079)?

**Comment by EmilieOlsen** [comment]
Hmm yes, agree. For the other apps, I want to stick with the pink due to its what we already have, and I think this works the best considering Equinors branding. But since this app more for "us", we can maybe keep the same layout, but use other colors. 
![image](https://github.com/equinor/mad/assets/111871753/b95888d0-aea4-41bb-9cd6-06e969573ebd)

What do you think?

**Comment by EmilieOlsen** [comment]
UPDATE:

Splash screen, Login screen, Login screen darkmode. 
![image](https://github.com/equinor/mad/assets/111871753/f6349b51-1d39-4a7a-8ddd-de23af796b21)

**Comment by HaakonSvane** [comment]
Hot stuff <3

**Comment by tormodAase** [comment]
Awesome!
