### ISSUE TITLE
Select language screen

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad#265]
### Package / App

MAD Components

### Description

Requirements:
- Should let the user select language
- Should be on the stack as a screen if app supports more than one language
- Settings screen should be able to navigate to it if app supports more than one language
- Should by default be an onboarding screen. Should also be possible to disable this feature in mad-config.

**Comment by EmilieOlsen** [comment]
I can look into it!

**Comment by EmilieOlsen** [comment]
Thoughts?

![image](https://github.com/equinor/mad/assets/111871753/b2d96208-e60b-4beb-be0a-7b4c0c20975a)

**Comment by tormodAase** [comment]
Looks great! We'll go with that one!
