### ISSUE TITLE
Service Message

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad#266]
### Package / App

Other

### Description

Requirements:
- Should be placed in `mad-core`'s custom sub-header component
- Should display a service message if it's available
- Should follow design found [here](https://www.figma.com/file/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?node-id=836%3A62385&mode=dev)
- Should check for new service messages frequently (I believe mad-expo-core does it every 5 minutes)

**Comment by dansvend** [comment]
Blocked by #232

**Comment by tormodAase** [comment]
This is no longer blocked by #232 , however there are some things that need clarification before we can start on this issue.

- How should the service message banner behave if the text is too long? Should the user be able to expand it?
- How should we display the link/URL attached to the service message?
- How should the user be able to remove the service message from the screen?

These things should be reflected in the design before we can start on this issue.
@EmilieOlsen

**Comment by EmilieOlsen** [comment]
Suggestion:

https://github.com/equinor/mad/assets/111871753/38d720ce-d46a-4dbd-b62d-246b3ae29ecb

- Dismiss should only be possible for a less important messages. If it's full error-message, dismiss should not be possible.
- ![image](https://github.com/equinor/mad/assets/111871753/7ec07870-f0a9-495f-b2b0-dd675d00e994)

- User should be "forced" to expand and read the whole service message before being able to dismiss
- If service message is short enough and do not need expand/collaps, 'dismiss' should be visible all the time.
- ![image](https://github.com/equinor/mad/assets/111871753/ae8b9b35-7afe-4e6e-9e43-eb0ea57a660c)

- URL, see video and picture below. 
![image](https://github.com/equinor/mad/assets/111871753/8b8c678d-ac4a-4c93-8e85-42d8c1558038)

Other suggestions:
- swipe to remove?

Figms-link: https://www.figma.com/file/GmYi1qTwOkAM4ZyK5Bsj31/Component-library?type=design&node-id=541%3A38571&mode=design&t=b9Kl2fsJFVj7dae6-1
