### ISSUE TITLE
Chip content not visible in dark mode in "Active" chips

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad#343]
### Package / App

MAD Components

### Version

0.8.6

### What happened?

Light mode
![image](https://github.com/equinor/mad/assets/22524448/09c8f163-bc18-4e43-8792-3f792a526817)

Dark mode
![image](https://github.com/equinor/mad/assets/22524448/fce665ce-ba1c-4bb1-8b84-763df708378a)

**Comment by Sandtory** [comment]
i think this is an issue for other components aswell where the background and text color used in darkmode is the same or very similar. 
Found it in `Menu`, `Autocomplete` and `Switch`.
