### ISSUE TITLE
`@equinor/mad-insights` should let developers run `track` before app insights is initialised

### ISSUE THREAD

**Issue by tormodAase** [equinor/mad#397]
### Package / App

Other

### Description

App insights initialisation happens when the navigation system gets rendered. Some apps have `track` calls happening in `App.tsx`. We should make this possible by queueing up track calls before initialisation happens

**Comment by HaakonSvane** [comment]
Does the initialization have to happen so late?

**Comment by tormodAase** [comment]
If we want it to happen without the apps doing any additional work, then it has to happen after navigation gets initialised. The track calls would only be delayed by a few milliseconds, so it shouldn't be an issue
