### ISSUE TITLE
Remove displaying property row for `undefined` values in `WorkOrderCell`

### ISSUE THREAD

**Issue by HaakonSvane** [equinor/mad#405]
### Package / App

MAD DFW

### Version

latest

### What happened?

If you provide the WorkOrderCell with undefined values for its props, the corresponding property row still shows

 <img width="402" alt="Screenshot 2024-02-08 at 09 44 01" src="https://github.com/equinor/mad/assets/36899138/dabb33df-b9eb-4e1f-b658-bce2167684e1">
(Equipment ID is missing, so it is passed into the cell as `undefined` in this case)

**Comment by Sandtory** [comment]
this has been fixed in #378, closing this issue
