### ISSUE TITLE
The search icon gets highlighted when the search is disabled

### ISSUE THREAD

**Issue by Jonas-Omdal** [equinor/mad#424]
### Package / App

MAD Components

### Version

0.12.7

### What happened?

The search icon gets highlighted when you press the search when its disabled.
This only occurs on web.

**Steps to reproduce:**
- Go to the Search screen
- Press the disabled search bar
- Observe the magnifying glass icon

**Expected behavior: **
- Pressing the disabled search bar should not change the icons color

**Comment by Sandtory** [comment]
this seems to only apply for web @Jonas-Omdal
