### ISSUE TITLE
Add text color to `PropertyRow` value

### ISSUE THREAD

**Issue by Chibuzor-Nwemambu** [equinor/mad#489]
### Package / App

MAD Components

### Description

We currently have a situation where text is needed to be a different color when conditions are met. With the current solution for PropertyRow, we cannot implement that.

Is it possible to get a text color for value? This can also be implemented in the workordercell under mad-dfw
![Screenshot 2024-04-12 at 11 35 03](https://github.com/equinor/mad/assets/75029767/500b96d5-c292-473c-8df4-caf33f19b5ce)

**Comment by HaakonSvane** [comment]
Nice 👌 what is the requirement for having the text be red when in the work order cell? I think the work order cell should be responsible for conditionally coloring the fields according to these rules since they will probably apply to all apps that use them
