### ISSUE TITLE
As a developer, I would like to close the cell swipe group once a button is clicked

### ISSUE THREAD

**Issue by Chibuzor-Nwemambu** [equinor/mad#492]
### Package / App

MAD Components

### Description

![image](https://github.com/equinor/mad/assets/75029767/5fc0b3ea-32f1-40a0-8ffc-3d9ad5069423)

In workorders, when the user presses "Add bookmark", I would like the swipe group to close. It seems like this is not currently possible

**Comment by Chibuzor-Nwemambu** [comment]
@HaakonSvane @Sandtory Do you know if this is currently possible, or do we need to make some adjustments to `@equinor/mad-components`?

**Comment by HaakonSvane** [comment]
Seems we can close the swipable using a ref, but we need a nice way to do this when we have lists of swipable cells. Maybe include an optional `swipableRef` in the onPress prop of `BaseCellSwipeItemProps`? This way, the user can at least access the Swipable ref methods inside the onPress callback

**Comment by Chibuzor-Nwemambu** [comment]
Sounds good! @tormodAase will have a look at this today!
