### ISSUE TITLE
CreateIncidentScreen: Unable to view textfields while editing on smaller devices

### ISSUE THREAD

**Issue by HavardNot** [equinor/mad#511]
### Package / App

MAD Core

### Version

0.6.1

### What happened?

While editing textfields in CreateIncidentScreen on smaller devices, the keyboard is blocking the view of the textfield. Making it impossible to see changes in real time. This could be fixed by using [KeyboardAvoidingView · React Native](https://reactnative.dev/docs/keyboardavoidingview) or [react-native-keyboard-aware-scroll-view](https://www.npmjs.com/package/react-native-keyboard-aware-scroll-view)

### Other info

https://reactnative.dev/docs/keyboardavoidingview
https://www.npmjs.com/package/react-native-keyboard-aware-scroll-view

**Comment by tormodAase** [comment]
@fnKode You fixed this, right?
#552 https://github.com/equinor/mad/releases/tag/%40equinor%2Fmad-core%400.8.1

Can we close this issue?
