### ISSUE TITLE
Logout button returns error

### ISSUE THREAD

**Issue by Chibuzor-Nwemambu** [equinor/mad#578]
### Package / App

MAD Core

### Version

0.9.1

### What happened?

On the workorders app, when the logout button is clicked:
* On iOS it returns this dialog box and logout is impossible
![image](https://github.com/equinor/mad/assets/75029767/d0b6f03f-5b0f-4258-b39d-1e934a2e2ab9)

* On web it returns this error
![image](https://github.com/equinor/mad/assets/75029767/932c7cb3-13d7-4f32-8f57-4180bd3927cf)

### Other info

Notifications app which uses version `0.8.1` seems to work fine.

**Comment by tormodAase** [comment]
This is most likely an error that was introduced by experimental expo auth session implementation.
@HavardNot would you like to take a look at this when you're back from vacation? 😻
