### ISSUE TITLE
Modernize styling of Progress component

### ISSUE THREAD

**Issue by HaakonSvane** [equinor/mad#679]
### Package / App

MAD Components

### Description

Inspection app utilizes the Progress component heavily and there are some adjustments that would be nice to incorporate to give the component more of a modern look:

- Remove the default background color. This should ideally be left for the users to style themselves
- Enlarge progress title and indicator icon
- (up for discussion?) Move the "show more" button underneath the progress title and description on iOS
- Remove the progress line indicator when the progress component is collapsed¨

![Image](https://github.com/user-attachments/assets/ee4ea5f6-8a5c-4fdb-ba27-192430b41e83)

### Other info

Would like some feedback on this @EmilieOlsen

**Comment by Jonas-Omdal** [comment]
Minor thing:
Pressing the simulation buttons in the upload simulator affects the progress item above.


![Image](https://github.com/user-attachments/assets/38d46938-37ed-4be8-932b-7a1d74c27213)
